name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours
  workflow_dispatch:

permissions:
  contents: write # Required for pushing to the repository
  pages: write   # Required for GitHub Pages deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Create dist directory
      - name: Create dist directory
        run: mkdir -p dist

      # Generate the snake
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: mishmanners
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Show the status of the build for debugging
      - run: git status

      # Push changes to the output branch
      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          commit_message: "Update snake contribution graph"

      # Deploy to GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
